board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from todolist.views import PostsList
from user.views import Register

# /

urlpatterns = [
    path("", PostsList.as_view()),
    path("admin/", admin.site.urls),
    path("api/posts/", include("todolist.api.urls")),
    path("posts/", include("todolist.urls", namespace="posts")),
    path("user/", include("user.urls", namespace="user")),
    path("accounts/register", Register.as_view(), name="register"),
    path(
        "accounts/",
        include(
            ("django.contrib.auth.urls", "django.contrib.auth"), namespace="accounts"
        ),
    ),
    path("captcha/", include("captcha.urls")),
    path("api/token", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/auth/", include("djoser.urls.authtoken")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

todolist/api/urls.py
from django.urls import path

from . import views


# /api/posts/

urlpatterns = [
    path("", views.PostsListCreateAPIView.as_view()),
    path("<int:post_id>", views.OnePostAPIView.as_view()),
]

todolist/urls.py
from django.urls import path

from . import views

app_name = "todolist"

# /posts/
urlpatterns = [
    # ДЛЯ CBV нужно вызвать `.as_view()`
    path("", views.PostsList.as_view(), name="home"),
    path("create/", views.CreatePost.as_view(), name="create"),
    path("<int:post_id>/", views.ShowPost.as_view(), name="show"),
    path("<int:post_id>/edit/", views.EditPost.as_view(), name="edit"),
    path("<int:post_id>/delete/", views.DeletePost.as_view(), name="delete"),
    path("<int:post_id>/comment/add/", views.CommentAdd.as_view(), name="comment_add"),
]

user/urls.py
from django.urls import path

from . import views

# /user/

app_name = "user"

urlpatterns = [
    path(
        "confirm-email/<uidb64>/<token>",
        views.ConfirmRegisterView.as_view(),
        name="activate",
    ),
    path(
        "reset-password",
        views.ResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "confirm-reset-password/<uidb64>/<token>",
        views.ConfirmResetPasswordView.as_view(),
        name="reset-password-confirm",
    ),
]

todolist/models.py
from django.shortcuts import reverse
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        "user.User", on_delete=models.CASCADE, related_name="posts"
    )
    content = models.TextField()
    tags = models.ManyToManyField("todolist.Tag", related_name="posts")

    def get_absolute_url(self):
        return reverse("posts:show", kwargs={"post_id": self.id})

    class Meta:
        ordering = ["-created"]
        indexes = [models.Index(fields=["created"])]

    @property
    def comments_count(self) -> int:
        return self.comments.all().count()

    def __repr__(self):
        return f"Post: <{self.title}>"

    def __str__(self):
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=256)
    color = models.CharField(max_length=8, default="000000FF")

    def __repr__(self):
        return f"Tag: <{self.name}>"

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    username = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created"]

    def __str__(self):
        return self.content[:30]

    def __repr__(self):
        return f"Comment: <{self.username}> <{len(self.content)}>"

todolist/forms.py
from django import forms

from todolist.models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ["title", "tags", "content"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "tags": forms.SelectMultiple(attrs={"class": "form-control"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
        }

todolist/api/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from django_filters import rest_framework as rest_filters

from .filters import APIPostFilter
from .permisiion import IsOwnerOrCanUpdateDeletePost
from .serializers import PostListSerializer, OnePostSerializer
from ..models import Post


class PostsListCreateAPIView(generics.ListCreateAPIView):
    serializer_class = PostListSerializer
    queryset = Post.objects.all()
    permission_classes = [IsAuthenticatedOrReadOnly]
    filter_backends = [rest_filters.DjangoFilterBackend]
    filterset_class = APIPostFilter

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class OnePostAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    lookup_url_kwarg = "post_id"
    lookup_field = "pk"
    serializer_class = OnePostSerializer
    permission_classes = [
        IsAuthenticatedOrReadOnly,
        IsOwnerOrCanUpdateDeletePost,
    ]

todolist/views.py
from django.shortcuts import redirect, get_object_or_404, reverse
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Count
from django.db.models import QuerySet

from chatgpt.translators import Translator
from .forms import PostForm
from .models import Post, Comment
from .filters import PostFilter
from .paginator import CachedPaginator


class PostsList(generic.ListView):
    template_name = "todolist/home.html"
    context_object_name = "posts"
    page_kwarg = "p"
    cache_timeout = 50
    paginate_by = 30
    paginator_class = CachedPaginator

    def paginate_queryset(self, queryset, page_size):
        key_prefix = settings.CACHES["default"]["KEY_PREFIX"]

        paginator = self.get_paginator(
            queryset,
            page_size,
            orphans=self.get_paginate_orphans(),
            allow_empty_first_page=self.get_allow_empty(),
            cache_name=f"{key_prefix}.CachedPaginator.posts_count",
            cache_timeout=self.cache_timeout,
        )
        page_number = (
            self.kwargs.get(self.page_kwarg)
            or self.request.GET.get(self.page_kwarg)
            or 1
        )

        page = paginator.page(page_number)
        page_object_list = self.get_cached_page_object_list(page)

        return paginator, page, page_object_list, page.has_other_pages()

    def get_cached_page_object_list(self, page):
        # Названия ключа для кэша
        cache_key = f'{settings.CACHES["default"]["KEY_PREFIX"]}.PostsList.{self.request.get_full_path()}'

        page_object_list = cache.get(cache_key)
        if page_object_list is None:
            page_object_list = list(page.object_list)  # Обращение к БД
            cache.set(cache_key, page_object_list, timeout=self.cache_timeout)

        return page_object_list

    def get_queryset(self) -> QuerySet[dict]:
        """
        Формирует `QuerySet` всех заметок и возвращает поля `id`, `title`, `created`,
        имя пользователя, создавшего заметку и кол-во комментариев к ней.

        :return Возвращает `QuerySet` словарей.
        """
        return PostFilter(
            self.request.GET,
            queryset=Post.objects.all()
            .select_related("user")
            .annotate(Count("comments"))
            .values("id", "title", "created", "user__username", "comments__count")
            .order_by("-comments__count"),
        ).qs


class ShowPost(generic.DetailView):
    queryset = Post.objects.prefetch_related("tags")  # Откуда вытянуть
    pk_url_kwarg = "post_id"  # Где брать ID объекта в URL?  Из `urls.py`!
    template_name = "todolist/show_post.html"  # Шаблон, куда вернуть
    context_object_name = "post"  # Под каким именем вернуть в шаблон

    def get_object(self, queryset=None):
        post: Post = super().get_object(queryset)
        # Перевод заметки
        post.content = Translator(post.content).to_eng()
        return post


@method_decorator(login_required, name="dispatch")
class DeletePost(generic.DeleteView):
    queryset = Post.objects
    model = Post
    pk_url_kwarg = "post_id"  # Где брать ID объекта в URL?  Из `urls.py`!
    success_url = reverse_lazy("posts:home")

    def form_valid(self, form):
        if self.object.user != self.request.user:
            return HttpResponseForbidden()
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class CreatePost(generic.CreateView):
    model = Post
    form_class = PostForm
    pk_url_kwarg = "post_id"
    template_name = "todolist/edit_post.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class EditPost(generic.UpdateView):
    model = Post
    form_class = PostForm
    pk_url_kwarg = "post_id"
    template_name = "todolist/edit_post.html"


class CommentAdd(generic.View):
    def post(self, request, post_id: int):
        post = get_object_or_404(Post, id=post_id)

        user = request.POST.get("user", "")
        email = request.POST.get("email", "")
        content = request.POST.get("content", "")

        Comment.objects.create(username=user, email=email, content=content, post=post)
        return redirect(reverse("posts:show", kwargs={"post_id": post.id}))

templates/todolist/comments_form.html
<p style="text-align: center">
  <a class="btn btn-outline-primary" data-bs-toggle="collapse" href="#commentForm" role="button" aria-expanded="false" aria-controls="commentForm">
    Оставить комментарий
  </a>
</p>

<div class="collapse" id="commentForm">
    <form action="{% url 'posts:comment_add' post_id %}" method="post">

        {% csrf_token %}

        <div class="mb-3">
          <label for="username-id" class="form-label">Username</label>
          <input type="text" required name="user" class="form-control" id="username-id">
        </div>
        <div class="mb-3">
          <label for="email-id" class="form-label">Email address</label>
          <input type="email" required name="email" class="form-control" id="email-id" placeholder="name@example.com">
        </div>
        <div class="mb-3">
          <label for="comment-id" class="form-label">Comment</label>
          <textarea class="form-control" required name="content" id="comment-id" rows="3"></textarea>
        </div>

        <button type="submit" class="btn btn-outline-success">
            Отправить
        </button>

    </form>
</div>

templates/todolist/comments_list.html
<h4>Комментарии</h4>
<div class="list-group">

    {% for comment in comments %}
        <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
          <img src="https://ui-avatars.com/api/?size=48&name={{ comment.username }}&font-size=0.33&background=random&rounded=true" class="center-block" alt="{{ comment.username }}">
          <div class="d-flex gap-2 w-100 justify-content-between">
            <div>
              <h6 class="mb-0">{{ comment.username }} ({{ comment.email }})</h6>
              <p class="mb-0 opacity-75">{{ comment.content }}</p>
            </div>
            <small class="opacity-50 text-nowrap">{{ comment.created }}</small>
          </div>
        </a>

    {% empty %}

        <h6 style="text-align: center">У этой заметки пока нет комментариев</h6>

    {% endfor %}

</div>

templates/todolist/create_edit_post.html
{% extends "base.html" %}

{% block content %}

<div class="container w-50 m-auto">

    <form method="post">

        {% csrf_token %}

        <div class="mb-3">
            <div class="input-group has-validation">
              <div class="form-floating {% if validator and not validator.title.is_valid %}is-invalid{% endif %}">

                <input type="text" name="title" id="note-title" value="{{ validator.title.value }}"
                       class="form-control {% if validator and not validator.title.is_valid %}is-invalid{% endif %}">
                <label for="note-title">Заголовок</label>
              </div>

            {% if validator and not validator.title.is_valid %}
              <div class="invalid-feedback">
                {% for error in validator.title.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}

            </div>
        </div>

        <div class="mb-3">
            <div>
                <select name="tags" class="form-select" multiple aria-label="multiple select example">
                    <option selected>Open this select menu</option>
                    {% for tag_name in tags_list %}
                        <option value="{{ tag_name }}">{{ tag_name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="mb-3">

            <div class="input-group has-validation">

                <div class="form-floating {% if validator and not validator.content.is_valid %}is-invalid{% endif %}">
                    <textarea class="form-control {% if validator and not validator.content.is_valid %}is-invalid{% endif %}"
                              name="content" id="note-content" rows="6">{{ validator.content.value }}</textarea>
                    <label for="note-content" class="form-label">Содержимое заметки</label>
                </div>

                {% if validator and not validator.content.is_valid %}
                  <div class="invalid-feedback">
                    {% for error in validator.content.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                  </div>
                {% endif %}
            </div>

        </div>

        <button class="btn btn-outline-success" type="submit">Создать</button>

    </form>
</div>

{% endblock %}

templates/todolist/edit_post.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container w-50">
        <form method="post">

            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-outline-success">Подтвердить</button>

        </form>
    </div>

{% endblock %}

templates/todolist/home.html
{% extends "base.html" %}

{% block content %}

{% include 'todolist/welcome.html' %}

<div class="container">

    <div class="g-3 row">

        {% for post in posts %}

            <div class="col">
                <div class="card shadow-sm" style="width: 18rem;">
                  <div class="card-body">
                    <h5 class="card-title">
                        {{ post.title }}
                    </h5>

                    <h6 class="card-subtitle mb-2 text-body-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="me-2" viewBox="0 0 16 16">
                          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
                        </svg>
                        {{ post.user__username }}
                    </h6>

                    <h6 class="card-subtitle mb-2 text-body-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="me-2" viewBox="0 0 16 16">
                          <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857V3.857z"></path>
                          <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
                        </svg>
                        {{ post.created|date:"D d M Y" }}
                    </h6>

                    <h6 class="card-subtitle mb-2 text-body-secondary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="me-2" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                          <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"></path>
                        </svg>
                        {{ post.comments__count }}
                    </h6>

                    <a href="{% url 'posts:show' post.id %}" class="btn btn-outline-primary">Посмотреть</a>

                    {% if post.user__username == request.user.username %}
                        <a href="{% url 'posts:edit' post.id %}" class="btn btn-outline-success">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                            </svg>
                            Изменить
                        </a>
                    {% endif %}

                  </div>
                </div>
            </div>

        {% empty %}

            <h2>Не найдено заметок</h2>

        {% endfor %}
    </div>
</div>


{% include 'paginator.html' %}

{% endblock %}

templates/todolist/show_post.html
{% extends "base.html" %}


{% block content %}

    <div class="container py-5">
        <h1 class="display-4">{{ post.title }}</h1>

        <span style="border-radius: 5px; background-color: #6f95e8; color: white; padding: 5px">
            {{ post.created }}
        </span>

        <div>
            {% for tag in post.tags.all %}
                <p class="badge bg-primary">{{ tag.name }}</p>
            {% endfor %}
        </div>

        {% if post.user == request.user %}

        <a href="{% url 'posts:edit' post.id %}" style="border-radius: 5px; background-color: #ffae7d; color: white; padding: 5px">
            Изменить
        </a>

        <form action="{% url 'posts:delete' post.id %}" method="post">
            {% csrf_token %}
            <input type="submit" style="border-radius: 5px; background-color: #ff7d7d; color: white; padding: 5px" value="Удалить">
        </form>

        {% endif %}

        <div style="margin: 20px">
            {{ post.content | safe }}
        </div>

    </div>

        <div class="b-example-divider"></div>

    <div class="container w-50">

        <br>

        {% include 'todolist/comments_list.html' with comments=post.comments.all %}

        <br>

        {% include 'todolist/comments_form.html' with post_id=post.id %}

    </div>

{% endblock %}

templates/todolist/welcome.html
{% load static %}

<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{% static 'img/welcome.png' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Смотрите чужие заметки</h1>
        <p class="lead">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">

            {% if request.user.is_authenticated %}
              <a href="{% url 'posts:create' %}" class="btn btn-success btn-lg px-4 me-md-2">
                  Создать новую
              </a>
            {% endif %}

        </div>
      </div>
    </div>
</div>