board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from todolist.views import PostsList
from user.views import Register

# /

urlpatterns = [
    path("", PostsList.as_view()),
    path("admin/", admin.site.urls),
    path("api/posts/", include("todolist.api.urls")),
    path("posts/", include("todolist.urls", namespace="posts")),
    path("user/", include("user.urls", namespace="user")),
    path("accounts/register", Register.as_view(), name="register"),
    path(
        "accounts/",
        include(
            ("django.contrib.auth.urls", "django.contrib.auth"), namespace="accounts"
        ),
    ),
    path("captcha/", include("captcha.urls")),
    path("api/token", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/auth/", include("djoser.urls.authtoken")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

todolist/urls.py
from django.urls import path

from . import views

app_name = "todolist"

# /posts/
urlpatterns = [
    # ДЛЯ CBV нужно вызвать `.as_view()`
    path("", views.PostsList.as_view(), name="home"),
    path("create/", views.CreatePost.as_view(), name="create"),
    path("<int:post_id>/", views.ShowPost.as_view(), name="show"),
    path("<int:post_id>/edit/", views.EditPost.as_view(), name="edit"),
    path("<int:post_id>/delete/", views.DeletePost.as_view(), name="delete"),
    path("<int:post_id>/comment/add/", views.CommentAdd.as_view(), name="comment_add"),
]

user/urls.py
from django.urls import path

from . import views

# /user/

app_name = "user"

urlpatterns = [
    path(
        "confirm-email/<uidb64>/<token>",
        views.ConfirmRegisterView.as_view(),
        name="activate",
    ),
    path(
        "reset-password",
        views.ResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "confirm-reset-password/<uidb64>/<token>",
        views.ConfirmResetPasswordView.as_view(),
        name="reset-password-confirm",
    ),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'css/todolist/notes.css' %}" rel="stylesheet">
</head>
<body>

{% include "header.html" %}

{% block content %}
    Часть которая меняется в каждом шаблоне
{% endblock %}

{% include "footer.html" %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
  </footer>
</div>

templates/header.html
<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'posts:home' %}" class="nav-link px-2 link-secondary">Главная</a></li>
        {% if request.user.is_authenticated %}
          <li><a href="{% url 'posts:create' %}" class="nav-link px-2 link-secondary">Создать новую</a></li>
        {% endif %}
        </ul>

        <form action="{% url 'posts:home' %}" method="get"
              class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search"
                 value="{{ request.GET.search }}"
                 name="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">

          {% if request.user.is_authenticated %}
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          {% else %}
{#              АНОНИМ#}
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          {% endif %}

          </a>
          <ul class="dropdown-menu text-small">
              {% if request.user.is_authenticated %}
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
              {% else %}
                <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
</header>

templates/paginator.html
<footer class="text-center text-lg-start text-muted">
    <div class="container p-4">

        {% if page_obj.has_other_pages %}
        <nav aria-label="...">
          <ul class="pagination justify-content-center">

            {# Первая страница #}
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{% url 'posts:home' %}?p=1&s={{ search_str }}">1 << </a>
            </li>
            {% endif %}

            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
              <a class="page-link"
                 {% if page_obj.has_previous %}
                 href="{% url 'posts:home' %}?p={{ page_obj.previous_page_number }}&s={{ search_str }}"
                 {% endif %}
              >Предыдущая</a>
            </li>

            {# Предыдущая страница #}
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'posts:home' %}?p={{ page_obj.previous_page_number }}&s={{ search_str }}">{{ page_obj.previous_page_number }}</a>
                </li>
            {% endif %}


            {# Текущая страница #}
            <li class="page-item active" aria-current="page">
              <a class="page-link">{{ page_obj.number }}</a>
            </li>


            {# Следующая страница #}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'posts:home' %}?p={{ page_obj.next_page_number }}&s={{ search_str }}">{{ page_obj.next_page_number }}</a>
            </li>
            {% endif %}

            {# Запасная страница #}
            {% if page_obj.number|add:'1' < paginator.num_pages %}
            <li class="page-item">
                <a class="page-link" href="{% url 'posts:home' %}?p={{ page_obj.number | add:'2' }}&s={{ search_str }}">{{ page_obj.number|add:'2' }}</a>
            </li>
            {% endif %}

            {# Следующая страница #}
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
              <a class="page-link"
                 {% if page_obj.has_next %}
                 href="{% url 'posts:home' %}?p={{ page_obj.next_page_number }}&s={{ search_str }}"
                 {% endif %}
              >Следующая</a>
            </li>

            {# Последняя страница #}
            {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="{% url 'posts:home' %}?p={{ paginator.num_pages }}&s={{ search_str }}"> >> {{ paginator.num_pages }}</a>
            </li>
            {% endif %}

          </ul>
        </nav>
    {% endif %}
    </div>
</footer>